[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "google-cloud-integ-cursor"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
google-cloud-aiplatform = "*"
pip = ">=24.3.1,<25"
max = "*"
google-generativeai = "*"
