[tool.mypy]
ignore_missing_imports = true
ignore_errors = true
disallow_untyped_defs = false
check_untyped_defs = false
warn_return_any = false
warn_unused_configs = false

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''
