version: '3.8'

services:
  computer-use-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  # Streamlit web interface
      - "5900:5900"  # VNC server (for debugging)
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CLOUD_ML_REGION=${CLOUD_ML_REGION}
      - PYTHONPATH=/app
      - DISPLAY=:1
    volumes:
      - ./.anthropic:/app/.anthropic  # For API key storage
      - ./logs:/app/logs              # For application logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
