version: '3.8'

services:
  meta-cognitive-framework:
    build:
      context: ..
      dockerfile: config/Dockerfile
      target: dev # Build the "dev" stage by default
    ports:
      - "8501:8501"  # Streamlit
      - "8888:8888"  # Jupyter
    environment:
      - PYTHONPATH=/home/appuser/app/src/python # Adjusted paths for non-root user
      - MOJO_PATH=/home/appuser/app/src/mojo # Adjusted paths for non-root user
      - MPLBACKEND=Agg
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PYTHONBREAKPOINT=ipdb.set_trace
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ../data:/home/appuser/app/data # Adjusted paths for non-root user
      - ../logs:/home/appuser/app/logs # Adjusted paths for non-root user
      - ../notebooks:/home/appuser/app/notebooks # Adjusted paths for non-root user
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Development service
  dev:
    extends: meta-cognitive-framework
    command: ./dev.sh watch # Use the new dev.sh script
    volumes:
      - ../src:/home/appuser/app/src # Adjusted paths for non-root user
      - ../tests:/home/appuser/app/tests # Adjusted paths for non-root user
      - ../config:/home/appuser/app/config # Adjusted paths for non-root user
      - ../data:/home/appuser/app/data # Adjusted paths for non-root user
      - ../logs:/home/appuser/app/logs # Adjusted paths for non-root user
      - ../notebooks:/home/appuser/app/notebooks # Adjusted paths for non-root user
    environment:
      - PYTHONPATH=/home/appuser/app/src/python # Adjusted paths for non-root user
      - MOJO_PATH=/home/appuser/app/src/mojo # Adjusted paths for non-root user
      - MPLBACKEND=Agg
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PYTHONBREAKPOINT=ipdb.set_trace
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTEST_ADDOPTS="--color=yes"

  # Jupyter notebook service
  notebook:
    extends: meta-cognitive-framework
    command: ./dev.sh notebook # Use the new dev.sh script
    ports:
      - "8888:8888"
    volumes:
      - ../notebooks:/home/appuser/app/notebooks # Adjusted paths for non-root user
      - ../src:/home/appuser/app/src # Adjusted paths for non-root user
      - ../data:/home/appuser/app/data # Adjusted paths for non-root user

  # Streamlit visualization service
  viz:
    extends: meta-cognitive-framework
    command: ./dev.sh streamlit # Use the new dev.sh script
    ports:
      - "8501:8501"
    volumes:
      - ../src:/home/appuser/app/src # Adjusted paths for non-root user
      - ../data:/home/appuser/app/data # Adjusted paths for non-root user

  # Testing service
  test:
    extends: meta-cognitive-framework
    command: ./dev.sh test # Use the new dev.sh script
    volumes:
      - ../src:/home/appuser/app/src # Adjusted paths for non-root user
      - ../tests:/home/appuser/app/tests # Adjusted paths for non-root user
      - ../data:/home/appuser/app/data # Adjusted paths for non-root user
    environment:
      - PYTEST_ADDOPTS="--color=yes -v --cov=src/python --cov-report=term-missing"
