project:
  name: Generic Project Template
  version: 1.0.0
  description: A flexible, modular project template for various contexts

environments:
  development:
    logging:
      level: DEBUG
      format: json
    database:
      type: h2
      url: jdbc:h2:mem:devdb
      username: sa
      password: ''
    features:
      debug-mode: true
      mock-services: true

  staging:
    logging:
      level: INFO
      format: plain
    database:
      type: postgresql
      url: jdbc:postgresql://staging-db.example.com/stagingdb
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    features:
      debug-mode: false
      mock-services: false

  production:
    logging:
      level: WARN
      format: json
    database:
      type: postgresql
      url: jdbc:postgresql://prod-db.example.com/productiondb
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
    features:
      debug-mode: false
      mock-services: false

system:
  performance:
    max-threads: 8
    connection-pool:
      min-size: 2
      max-size: 20
      idle-timeout: 300000  # 5 minutes

security:
  authentication:
    type: jwt
    token-expiration: 3600  # 1 hour
  cors:
    allowed-origins:
      - https://example.com
      - http://localhost:3000
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed-headers:
      - Authorization
      - Content-Type

monitoring:
  health-checks:
    database:
      enabled: true
      interval: 60  # seconds
    external-services:
      enabled: true
      timeout: 5000  # milliseconds

feature-flags:
  advanced-logging: false
  performance-tracing: true
  experimental-features: false

extensions:
  plugin-directory: ./plugins
  auto-load-plugins: true
