name: Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'computer-use-demo/**'
      - '.github/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'computer-use-demo/**'
      - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r computer-use-demo/computer_use_demo/requirements.txt
        pip install pytest pytest-asyncio pytest-cov ruff mypy types-prometheus-client

    - name: Run linters
      run: |
        # Run ruff for Python linting
        ruff check computer-use-demo/computer_use_demo/
        # Run mypy for type checking
        mypy --ignore-missing-imports computer-use-demo/computer_use_demo/

    - name: Run tests with coverage
      run: |
        pytest computer-use-demo/tests/ \
          --cov=computer-use-demo/computer_use_demo/ \
          --cov-report=xml \
          --cov-report=term-missing \
          --asyncio-mode=auto

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
